### PR TITLE
Fix issue with empty target path

### LINKED ISSUE #38: Problem with target_path feature
As mentionned in #35 by @aleksandrs-ledovskis 

> If target_path is "" (empty string), this prepends / to :key and causes all public/* files appear under extra "slash" directory when deploying, breaking sites. I.e. public/foo.bar will be placed in <bucket_name>//foo.bar.

### PR DESCRIPTION
**Pull request by kirillplatonov**
Fixes #38

### CODE REVIEW

File: lib/capistrano/s3/publisher.rb [hunk 1]
```diff
@@ -110,7 +112,7 @@ def self.put_object(s3, bucket, target_path, path, file, only_gzip, extra_option
           mime_type = mime_type_for_file(base_name)
           options   = {
             :bucket => bucket,
-            :key    => File.join(target_path, path),
+            :key    => self.add_prefix(path, prefix: target_path),
```
Comment (aleksandrs-ledovskis) [inline lib/capistrano/s3/publisher.rb]: No need to write `self`. Per [RSG](https://github.com/bbatsov/ruby-style-guide/blob/master/README.md#class-and-self)

Comment (kirillplatonov) [inline lib/capistrano/s3/publisher.rb]: Yes, but it's how current code in this library styled. I think it will be good to separate style changes into another PR.

Comment (aleksandrs-ledovskis) [inline lib/capistrano/s3/publisher.rb]: Agree, will handle in #43

**Comment by aleksandrs-ledovskis** [comment]
LGTM
